### ISSUE TITLE
Create page items comtainers and borders

### ISSUE THREAD

**Issue by mahaelbasuony** [mahaelbasuony/twitter-clone#2]
- center item to have borders right and left
- to have in the right column 3 boxes with the write with and height also have to have the right border style
- create a container in the left hand side that contain the logo and the main links and the tween button area
- create a box in the bottom of the left column for the user profile

- keep in mind all the apaces `paddings` and `margins`

**Comment by medhatdawoud** [comment]
Good references that would help in the challenges of this task

- Margins: https://developer.mozilla.org/en-US/docs/Web/CSS/margin
- Padding: https://developer.mozilla.org/en-US/docs/Web/CSS/padding
- Postions: https://developer.mozilla.org/en-US/docs/Web/CSS/position
- Border: https://developer.mozilla.org/en-US/docs/Web/CSS/border

Feel free to read these resources either ahead before the task to get an idea and refresh yourself and keep looking into them every time you forget something ;)
